### ISSUE TITLE
Update bn.js to 4

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/crypto-browserify#140]
~~big number had  a major version bump a while back which I've avoided bothering with upgrading to but I just landed 2 new curves in elliptic which relies on the new version so I guess it's time to upgrade.  The idea would be to do major version bumps in the libraries and then upgrade the deps of crypto-browserify in a single go~~

and it bumped again (i suspect my work upgrading all this and with elliptic caused @indutny look more at bn.js inadvertently causing the bump). So back to square one but this time I know exactly what I need to do.
- [x] upgrade miller-rabin
- [x] upgrade browserify-rsa crypto-browserify/browserify-rsa#6
- [x] upgrade public-encrypt crypto-browserify/publicEncrypt#10
- [x] upgrade create-ecdh crypto-browserify/createECDH#7
- [x] upgrade diffie-hellman crypto-browserify/diffie-hellman#19
- [x] upgrade browserify-sign 
- [x] upgrade asn1.js
- [x] upgrade parse-asn1 crypto-browserify/parse-asn1#17
- [x] fix issue with der encoding of p521 signatures and upgrade elliptic indutny/elliptic#58
- [ ] upgrade crypto-browserify

**Comment by calvinmetcalf** [comment]
browserify-rsa seems to have an issue

**Comment by calvinmetcalf** [comment]
browserify-sign is waiting on indutny/elliptic#58

**Comment by calvinmetcalf** [comment]
round 2.1 is done, parse-asn1 is blocking  browserify-sign browserify-rsa and public-encrypt

**Comment by calvinmetcalf** [comment]
last 2 rely on rsa

**Comment by dcousens** [comment]
@calvinmetcalf all done?
